version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - hello_fastapi:/var/lib/postgresql/data
    networks:
      hello_fastapi:
        ipv4_address: 172.21.0.2
networks:
  hello_fastapi:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
volumes:
  hello_fastapi:
