version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.1"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "53603:53603"
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
