"""Add user model

Revision ID: e6a8e7cf7f6c
Revises: 89f4c65419b2
Create Date: 2021-01-18 20:28:32.974148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a8e7cf7f6c'
down_revision = '89f4c65419b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('HashedPassword', sa.String(), nullable=False),
    sa.Column('FullName', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsSuperUser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_Id'), 'Users', ['Id'], unique=False)
    op.create_index(op.f('ix_Users_Username'), 'Users', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_Username'), table_name='Users')
    op.drop_index(op.f('ix_Users_Id'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
