"""Init database

Revision ID: ee0eae2e43c3
Revises: 
Create Date: 2021-01-15 17:59:42.776504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0eae2e43c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Schools',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=True),
    sa.Column('EstablishedDate', sa.Date(), nullable=True),
    sa.Column('Address', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Schools_Id'), 'Schools', ['Id'], unique=False)
    op.create_table('Grades',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('SchoolId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SchoolId'], ['Schools.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Grades_Id'), 'Grades', ['Id'], unique=False)
    op.create_table('Students',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Gender', sa.Boolean(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('GradeId', sa.Integer(), nullable=True),
    sa.Column('SchoolId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GradeId'], ['Grades.Id'], ),
    sa.ForeignKeyConstraint(['SchoolId'], ['Schools.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Students_Id'), 'Students', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Students_Id'), table_name='Students')
    op.drop_table('Students')
    op.drop_index(op.f('ix_Grades_Id'), table_name='Grades')
    op.drop_table('Grades')
    op.drop_index(op.f('ix_Schools_Id'), table_name='Schools')
    op.drop_table('Schools')
    # ### end Alembic commands ###
